#!/bin/sh

set -e

. ./zsh/zshenv

export INSTALL="$DOTFILES"/installation

. "$INSTALL"/colors.sh
. "$INSTALL"/functions.sh

dot_info "Pull last commits"
git pull -q
dot_info "Update submodules"
git submodule update --init
dot_info "Check update submodules"
submodules=$(grep -oP '^\[submodule "\K[^"]*' .gitmodules)
for submodule in $submodules; do
    dot_info "Check update $submodule"
    if exists_in_list "NvChad" " " "$submodule"; then
      update_submodule_rolling "$submodule"
    else
      update_submodule "$submodule"
    fi
done


if [ $# -ne 0 ]; then

    for p in "$@"; do
        dot_install "$p"
    done

else
    dot_confirm "Overwrite configuration" || ( dot_warn "Aborting"; exit 1 )

    # Install the configuration files
    dot_install locale
    dot_install zsh
    dot_install clang-format
    dot_install nvim
    dot_install gdb

    dot_is_installed git          && dot_install git
    dot_is_installed dunst        && dot_install dunst
    dot_is_installed kitty        && dot_install kitty
    dot_is_installed i3           && dot_install i3
    dot_is_installed i3status     && dot_install i3status
    dot_is_installed ssh          && dot_install ssh
    dot_is_installed gpg          && dot_install gpg
    dot_is_installed wget         && dot_install wget
fi
