#!/bin/sh

set -e

. ./zsh/zshenv

export INSTALL="$DOTFILES/installation"

. "installation/colors.sh"
. "installation/functions.sh"

if [ $# -ne 0 ]; then

	for p in "$@"; do
		dot_install "$p"
	done

else
	dot_confirm "Overwrite configuration" || (
		dot_warn "Aborting"
		exit 1
	)

	# Install the configuration files
	dot_install locale
	dot_install zsh
	dot_install clang-format
	dot_install nvim
	dot_install gdb
	dot_install python
	dot_install helix

	dot_is_installed git && dot_install git
	dot_is_installed dunst && dot_install dunst
	dot_is_installed kitty && dot_install kitty
	dot_is_installed i3 && dot_install i3
	dot_is_installed i3status && dot_install i3status
	dot_is_installed ssh && dot_install ssh
	dot_is_installed gpg && dot_install gpg
	dot_is_installed wget && dot_install wget
fi
