#!/bin/sh

set -e

. ./zsh/zshenv

export INSTALL="$DOTFILES"/installation

. "$INSTALL"/colors.sh
. "$INSTALL"/functions.sh

dot_info "Pull last commits"
git pull -q
dot_info "Update submodules"
git submodule update --init
dot_info "Check update submodules"
update_submodule ./powerlevel10k/
update_submodule ./zsh-vi-mode/


if [ $# -ne 0 ]; then

    for p in "$@"; do
        dot_is_installed "$p" && dot_install "$p"
    done

else
    dot_confirm "Overwrite configuration" || ( dot_warn "Aborting"; exit 1 )

    # Install the configuration files
    dot_install zsh
    dot_install clang-format
    dot_install nvim

    dot_is_installed git          && dot_install git
    dot_is_installed i3           && dot_install i3
    dot_is_installed i3status     && dot_install i3status
    dot_is_installed kitty        && dot_install kitty
    dot_is_installed ssh          && dot_install ssh

fi
