#!/bin/sh

set -e

. ./zsh/zshenv

export INSTALL="$DOTFILES"/installation

. "$INSTALL"/colors.sh
. "$INSTALL"/functions.sh

dot_info "Pull last commits"
git pull -q
dot_info "Update submodules"
git submodule update --init
dot_info "Check update submodules..."
submodules=$(grep -oP '^\[submodule "\K[^"]*' .gitmodules)
for submodule in $submodules; do
	if exists_in_list "NvChad zsh-autosuggestions" " " "$submodule"; then
		dot_info "Check update $submodule - Rolling"
		update_submodule_rolling "$submodule"
	else
		dot_info "Check update $submodule - Tag"
		update_submodule "$submodule"
	fi
done
