theme = "kanagawa"

[editor]
line-number = "relative"
mouse = true
rulers = [80]
text-width = 80
bufferline = "multiple"
popup-border = "none"
auto-pairs = false
# end-of-line-diagnostics = "error"

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"
max-diagnostics = 3

[editor.statusline]
left = [
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["diagnostics", "file-type", "workspace-diagnostics"]
right = ["selections", "register", "position", "file-encoding"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # Enables ignoring hidden files
parents = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
tabpad = "·"

[editor.smart-tab]
enable = false

[editor.indent-guides]
render = true
character = '▏'
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
X = "extend_line_above"
G = "goto_file_end"

[keys.select]
G = "goto_file_end"
