vim.g.grammalecte_cli_py = "/usr/sbin/grammalecte-cli"
vim.g.grammalecte_disable_rules =
	"apostrophe_typographique apostrophe_typographique_après_t typo_points_suspension1 typo_tiret_incise nbsp_avant_double_ponctuation nbsp_avant_deux_points nbsp_après_chevrons_ouvrants nbsp_avant_chevrons_fermants1 typo_guillemets_typographiques_doubles_ouvrants typo_guillemets_typographiques_doubles_fermants unit_nbsp_avant_unités1"
