#!/usr/bin/env zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# history
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt INC_APPEND_HISTORY
setopt BANG_HIST
HISTSIZE=50000
SAVEHIST=10000

bindkey -v
bindkey '^R' history-incremental-pattern-search-backward

# directory stack
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index


# source aliases
source $XDG_CONFIG_HOME/aliases.sh

# zsh vi mode
source $DOTFILES/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# zsh hist
source $DOTFILES/zsh-hist/zsh-hist.plugin.zsh

# prompt
source $DOTFILES/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f $ZDOTDIR/.p10k.zsh ]] || source $ZDOTDIR/.p10k.zsh

# path
path=("$HOME/.nimble/bin" "$HOME/bin" $path)
export PATH

# start ssh-agent
eval `ssh-agent -t 3600` > /dev/null

# enable autocompletion
autoload -Uz compinit; compinit; _comp_options+=(globdots);
