#!/usr/bin/env zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt HIST_SAVE_NO_DUPS
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward

# directory stack
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

#bindkey -a '^[[3~' vi-delete-char
#bindkey "^[[1;5D" backward-word
#bindkey "^[[1;5C" forward-word

source $DOTFILES/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# enable autocompletion
autoload -Uz compinit; compinit; _comp_options+=(globdots);

# source aliases
. $XDG_CONFIG_HOME/aliases.sh

# prompt
# . $ZDOTDIR/prompt.sh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f $ZDOTDIR/.p10k.zsh ]] || source $ZDOTDIR/.p10k.zsh
