#!/usr/bin/env zsh

setopt HIST_SAVE_NO_DUPS

# directory stack
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# enable autocompletion
autoload -Uz compinit; compinit; _comp_options+=(globdots);

# source aliases
. $XDG_CONFIG_HOME/aliases.sh

# fix ctrl+arrow
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# prompt
. $ZDOTDIR/prompt.sh
